modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="dragonblockinfinity"
version="1.0.0"
displayName="Dragon Block Infinity"
authors="Bernardo"
description='''
Dragon Ball Mod para NeoForge 1.21.1
'''
